trigger:
  branches:
    include:
      - "*"

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials: true
    fetchDepth: 0

  - script: |
      git config --global user.email "automation@ofima.com"
      git config --global user.name "Ofima Mirror Bot"

      git remote remove github || true
      git remote add github https://dsdiaz447:$(GITHUB_PAT)@github.com/Admin-gthb-ofima/architecture-templates-mirror.git

      git fetch origin --prune
      git push github +refs/remotes/origin/*:refs/heads/* --prune
      git push github --tags
    displayName: "Mirror Azure Repos to GitHub"